config/routes.rb
Roblog::Application.routes.draw do |map|
  
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  resources :user, :controller => 'user'

  root :to => "articles#index"

  
  resources :authors do
    resources :articles, :only => ["index", "show"]
  end
  
  resources :articles, :only => ["index", "show"]  do
    resources :comments
    resources :tags

  end

  resources :tags do
    resources :articles do
      collection do
        get "tagged"
      end

      member do
        delete "untag"
      end
    end
  end

  
  resources :roles
  
  resources :adminarticles, :namespace => "admin", :controller => 'admin_console'
  
  match "tags/lookup" => "tags#lookup"
  

end

app/models/article.rb
#require "RedCloth"
#require "digest/sha2"
require "digest/md5"
require "uv"

class Article < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  has_and_belongs_to_many :tags # , :join_table => "articles_tags", :foreign_key => "tag_id"
  belongs_to :author, :class_name => "Author", :foreign_key => "author_id"

  #callbacks
  before_save :check_body

  def add_comment(c)
    #comment = Comment.new
    #comment.body = hash[:text]
    #comment.user_id = hash[:user]
    #puts "Article id: #{self.id}, Comment Body: #{comment.body}"
    #comment.article_id = self.id
    self.comments << c
    self.save
  end
  
  def delete_comment(cid)
    comment = nil
    self.comments.each {|cn| comment = cn if cn.id == cid}
    self.comments.delete(comment)
    self.save
    
  end
  
  #My hope is that after implementing a caching mechanism, this won't really matter.
  #This could be a potential bottleneck since entire blog posts will be passed through this
  #markup tool.  If it doesn't work out, I will save both a textile and html version in the DB.
  def render_to_html
    #RedCloth.new(self.body).to_html
    if self.body_html?
      self.body_html
    else
      check_body
      self.save
      self.body_html
    end
  end
  
  def publish_it
    self.published = true
    self.save
  end
  
  def edit_mode
    self.published = false
    self.save
  end
  
  def add_tag(tag)
    self.tags << tag
    self.save
  end
  
  def remove_tag(tag)
    self.tags.delete(tag)
    self.save
  end
  
  def get_status
    if self.published? then
      return "published"
    else
      return "draft"
    end
  end

  def process_body(text, options = {})
      text_pieces = text.split(/(<code>|<code lang="[A-Za-z0-9_-]+">|
        <code lang='[A-Za-z0-9_-]+'>|<\/code>)/)
      #text_pieces.each_with_index{|p,i| puts "[#{i}]>> #{p}"}
      in_pre = false
      language = nil
      text_pieces.collect do |piece|
        if piece =~ /^<code( lang=(["'])?(.*)\2)?>$/
          language = $3
          in_pre = true
          nil
        elsif piece == "</code>"
          in_pre = false
          language = nil
          nil
        elsif in_pre
          #puts "IN PRE: text piece = #{piece}"
          lang = language ? language : "ruby"
          #code(piece.strip, :lang => lang)
          Uv.parse( piece, "xhtml", lang, true, "blackboard")
        else
          markdown(piece, options)
        end
      end.join("")
    end

    def markdown(text, options = {})
      if options[:split]
        RDiscount.new(strip_tags(text.strip)).to_html
      else
        RDiscount.new(text.strip).to_html
      end
    end


  private

  def check_body
    #digest = Digest::SHA2.new do |d|
    #   d << self.body
    #end
    digest = Digest::MD5.hexdigest(self.body)

    if self.checksum != digest
      self.checksum = digest
      self.body_html = process_body(self.body)
    end

  end

  def increment_tags_counter_cache
    Tag.increment_counter(:articles_count, self.id)
  end



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_filter :authenticate_user!, :only => ["index", "show", "tagged"]
  #skip_before_filter :check_authorization#, :only => ["index", "show"]
  load_and_authorize_resource
  respond_to :html, :xml
  layout "articles"
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    #respond_to do |format|
    #  format.html # show.html.erb
    #  format.xml  { render :xml => @article }
    #end
    
    respond_with(@article)
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    if(user_signed_in?)
      @article = Article.new
      @user = User.find(current_user.id)
      
      if !@user.author
        @author = @user.build_author
        @author.pseudo_last = @user.last_name
        @author.pseudo_first = @user.first_name
        @author.save
      end
      
      #add the article to the user
      respond_with(@article)
    end

    #respond_to do |format|
    #  format.html # new.html.erb
    #  format.xml  { render :xml => @article }
    #end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    if user_signed_in?
      @article = Article.new(params[:article])
      @user = User.find(current_user.id)
      @user.author.articles << @article
      respond_with(@article)
    end

    #respond_to do |format|
    #  if @article.save
    #    format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
    #    format.xml  { render :xml => @article, :status => :created, :location => @article }
    #  else
    #    format.html { render :action => "new" }
    #    format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
    #  end
    #end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end

  def untag
    @article = Article.find(params[:id])
    tag = Tag.find(params[:tag_id])
    @article.tags.delete(tag)
    tag.decrement_article_count
    render "tags/article_tags"
  end

  def tagged
    @tag = Tag.find(params[:tag_id])
    @articles = @tag.articles
    respond_to do |format|
      format.html { render("index")}
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  
  def generate_color_code
    hex_array = ["0","1","2","3","4","5","6","7","8","9","a","b","c","d","e","f"] #will be able to index hex digits with this
    max = hex_array.length #random number needs to be between 0 and 15
    
    #need to generate 6 characters
    code = '#'
    0.upto(5) {
      index = rand(max)
      code << hex_array[index]
    }
    code + ";"
  end
  
  def create_blocks(p_hash)
    rows = p_hash[:rows]
    columns = p_hash[:columns]
    width = p_hash[:width]
    height = p_hash[:height]
    css_class = p_hash[:class]
    
    top = 0
  	left = 0
  	html = ""
    0.upto(rows - 1) do |row|
      0.upto(columns -1) do |col|
        html += "<div id='block_#{row}_#{col}'"
        html += " class='#{css_class}' " if css_class
        html += "style='width: #{width}px; height: #{height}px; top: #{top}px; left: #{left}px; background-color: #{generate_color_code}'></div>\n"
        left = left + width
      end
      top = top + height
      left = 0
    end
    
    html.html_safe
  end
  
  def format_code
    
  end
  
end

app/views/articles/_article_comments.html.erb
<div id="comments" class="article-body">
  <h3 class="light-grey-font dotted-underline" style="width: 100%;">Comments</h3>
  <%  @article_comments.each do |comment| %>
    <div class="comment-body">
		<p class="big-font"><%= User.find(comment.user_id).username %></p>
		<p class="big-font"><%= comment.created_at %></p>
		<p class="med-font"><%= comment.body %></p>
		
	</div>
  <% end %>

  <div id="comments-form">
	<h3> Post a Comment </h3>
	<% form_tag(:controller => "comments", :action => "create", {:class => "form"}) do %>
	  <%= text_area_tag("body", )%>
	<% end -%>
  </div>
</div>

app/views/articles/_headerblocks.html.erb
<%
	dim = 25
	top = 0
	left = 0
%>

<%  
	0.upto(7) do |i|
		0.upto(34) do |j|
%>
	<div id="block_<%= i %>_<%= j %>" class="block" style="top:<%= top %>px; left:<%= left %>px; background: <%= generate_color_code %>"></div>
<%
			left = left + dim
		end
		top = top + dim
		left = 0
	end
%>





	

app/views/articles/_tag_cloud.html.erb
<div id="tag_cloud" class="">
  <p class="light-grey-font big_font dotted-underline">
       All tags:
     </p>
  <% tags = Tag.all	  %>
  <ul>
    <% tags.each do |tag| %>
        <% puts "TAG: #{tag.tag_name} " %>
    <%	 if tag.deviations < -1  %>
            <li class="micro_font"><%= link_to tag.tag_name, tagged_tag_articles_path(tag) %></li>
    <%	 elsif tag.deviations >= -1 && tag.deviations < 1 %>
            <li class="med_font"><%= link_to tag.tag_name, tagged_tag_articles_path(tag) %></li>
    <%	 else  %>
            <li class="huge_font"><%= link_to tag.tag_name, tagged_tag_articles_path(tag) %></li>
    <%	 end  %>
    <% end %>

  </ul>
</div>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% if @tag %>
   <p class="med_font dotted-underline">Articles tagged with: <span class="dark-green-font"><%= @tag.tag_name  %></span></p>
<% end %>
<% @articles.each do |article| %>
 	<% if article.published?%>
    <div class="article">
    <h2 class="light-grey-font big_font"><%= link_to article.title, article, {:class => "light-grey-font"} %></h2>
	<p class="light-grey-font small_font">posted at: <%= article.created_at.strftime('%D')%></p>
	<% if article.author %>
		<% if article.author.pseudo_first != "" %>
	<p class="light-grey-font small_font">by: <%= article.author.pseudo_first  %>&nbsp;<%= article.author.pseudo_last %></p>
		<% else%>
	<p class="light-grey-font small_font">by: <%= article.user.username  %></p>
		<% end %>
	<% end %>
	
	<p class="light-grey-font med_font"><%= article.synopsis %></p>
	</div>
	<% end %>
<% end %>
	

app/views/articles/show.html.erb
<p class="light-grey-font huge_font dotted-underline">
  <%= @article.title %>
</p>

<div id="tags_div" class="article_tag_list light-grey-font article-font">
  <p id="tags_title">Articles tagged with: </p>
  <ul id="tags_list">
     <%	 @article.tags.each do |tag| %>
    <li><%= link_to tag.tag_name, tagged_tag_articles_path(tag) %></li>
     <%	 end %>
  </ul>
</div>

<!-- The article body -->
<div class="article-body white-font article-font">
  <%= sanitize @article.render_to_html %>
</div>
<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Froblog.com&amp;send=true&amp;layout=standard&amp;width=450&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font=lucida+grande&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe>

<!-- The list of comments -->
<div class="article-body white-font med_font">
	<h3 class="light-grey-font dotted-underline" style="width: 100%;">Comments</h3>
	<% if @article.comments.count > 0 %>
		<%= render :partial => "comments/comment", :collection => @article.comments %>
	<% else %>
		<p class="white-font small_font">There are no comments on this article yet</p>
	<% end %>
	
	<% if !@article.comments || @article.comments.count <= 0
		comment = Comment.new
	else
		comment = @article.comments[0]
	end %>

</div>



<div id="comment-form" class="article-body clear">
 	<%= render :partial => "comments/form", :object => @article %>
</div>