config/routes.rb
Roblog::Application.routes.draw do |map|
  
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  resources :user, :controller => 'user'

  root :to => "articles#index"

  
  resources :authors do
    resources :articles, :only => ["index", "show"]
  end
  
  resources :articles, :only => ["index", "show"]  do
    resources :comments
    resources :tags

  end

  resources :tags do
    resources :articles do
      collection do
        get "tagged"
      end

      member do
        delete "untag"
      end
    end
  end

  
  resources :roles
  
  resources :adminarticles, :namespace => "admin", :controller => 'admin_console'
  
  match "tags/lookup" => "tags#lookup"
  

end

app/views/layouts/admin_console.html.erb
<html>
	<head>
		<title>Blog Console</title>
      <%= csrf_meta_tag %>
		<%= stylesheet_link_tag "blog_styles_white" %>
		<%= stylesheet_link_tag "scaffold" %>
		<%= javascript_include_tag :defaults %>
        <%= javascript_include_tag "tag_management" %>
		<%= stylesheet_link_tag "ultraviolet/blackboard" %>
		
	</head>
	<body>
		<div id="admin_header" class="dashed-underline">
			<%= create_blocks :width => 25, :height => 25, :columns => 46, :rows => 2, :class => "block" %>
			<div id="admin_hdr_content">
				<ul class="nav med_font light-grey-font">
					<li><%= link_to "Published Articles", articles_path,{:class => "white"} %></li>
					
					<% if can? :update, @article %>
					<li><%= link_to "Article Index", adminarticles_path ,{:class => "white"}%></li>
					<% end %>
				
					<% if can? :create, @article %>
						<li><%= link_to "New Article", new_adminarticle_path,{:class => "white"}%></li>
					<% end %>
				
					<li><%= link_to "Logout", destroy_user_session_path,{:class => "white"}%></li>
					
					<% if can? :update, current_user %>
					<li>
						<%= link_to "Manage Users", user_index_path ,{:class => "white"} %>
					</li>
					<% end %>
					
					<% if can? :update, @role %>
					<li>
						<%= link_to "Manage Roles", roles_path ,{:class => "white"} %>
					</li>
					<% end %>
				</ul>
			</div>
		</div>
		
		<% if flash[:notice] %>
			<div class="errors">
				<%= flash[:notice] %>
			</div>
		<% end %>
		<%= yield %>
	</body>
</html>

app/views/layouts/articles.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= csrf_meta_tag %>
	<%= stylesheet_link_tag "blog_styles_white" %>
	<%= stylesheet_link_tag "scaffold" %>
	<%= javascript_include_tag :all %>
	<!--
	<%= stylesheet_link_tag "all" %>
	<%= javascript_include_tag 'all.js.bak' %>
	-->
	<%= stylesheet_link_tag "ultraviolet/blackboard" %>


	

	<script type="text/javascript">
		$(document).ready(
                    function(){

			            $('#notice-div').fadeOut(4000.0);
                        $('#error-div').fadeOut(4000.0)
		            }
                );
		
	</script>
</head>
<body>
	<div id="fb-root"></div>
	<script src="http://connect.facebook.net/en_US/all.js"></script>
	<script type="text/javascript" charset="utf-8">
		FB.init({appId: '160343384030567', 
						 cookie:true,
						 status:true,
						 xfbml:true
						})
	</script>
	<div id="header">
	 <%= create_blocks :width => 25, :height => 25, :columns => 46, :rows => 4, :class => "block" %>
		
		<div id="header_content" class="hdr_content solid-underline">
			
			
			<ul class="nav med_font white-font" id="nav_ul">
				<li>
					<p class="big_font opaque">~~~~~~~~~~EXOCORTEX~~~~~~~~~~</p>
				</li>
				<li>
					<%= link_to "Articles", "/", {:class => 'white'} %>
				</li>
				<li>
					<%if current_user %>
						<p>Hello <%=  current_user.first_name %></p>
					<% end %>
				</li>
				<li>
					<% if !current_user %>
						<%= link_to "Login", new_user_session_path %>	
						<%= link_to "Sign up", new_user_registration_path %>
						Or
						
						<%= link_to image_tag("facebook-login-button.png",:alt =>"Sign in with facebook"), user_omniauth_authorize_path(:facebook)%>
					<% else %>
					<%= link_to "Logout", destroy_user_session_path %>
					<% end %>
				</li>
				<% if current_user && ((current_user.role? :publisher) || (current_user.role? :superuser)) %>
				<li>
					<%= link_to "Administration", adminarticles_path %>
				</li>
				<% end %>
				
			</ul>
		</div>
		<% if flash[:notice] %>
			<div id="notice-div" class="notice blue-border">
				<p><%= flash[:notice] %></p>
			</div>
		<% end %>
		<% if flash[:error] %>
			<div id="error-div" class="errors red-border">
				<p><%= flash[:error] %> </p>
			</div>

		<% end %>
	</div>

    <div id="tag_cloud_container">

    <%= render :partial => 'articles/tag_cloud' %>
    </div>
	
	<div id="content" class="light-grey-font">
		<%= yield :layout %>
	</div>


</body>
</html>

app/views/layouts/blog_ui.html.erb
<html>
<head>
	<%= stylesheet_link_tag :all, :cache => true %>
</head>
<body>
	<div id="header">
	 <%= render(:partial => "headerblocks") %>
		
		<div id="header_content" class="hdr_content">
			<p class="huge_font opaque">RobLog: my own personal blog.</p>
			
			<ul class="nav med_font" id="nav_ul">
				<li>
					<%= link_to "Articles", :action => "index" %>
				</li>
				<li>
					<a href="#">navlink2</a>
				</li>
				<li>
					<a href="#">navlink3</a>
				</li>
				<li>
					<a href="#">navlink1</a>
				</li>
				<li>
					<a href="#">navlink2</a>
				</li>
				<li>
					<%= link_to "Login", :controller => "admin_console", :action => "login_form" %>
				</li>
			</ul>
		</div>
	
		
	</div>
	<div id="content" class="light-grey-font">
		<%= yield :layout %>
	</div>
</body>
</html>

app/views/layouts/comments.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comments: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<p class="notice"><%= notice %></p>

<%= yield %>

</body>
</html>